export const FETCH_ALL_EXERCISES = 'FETCH_ALL_EXERCISES';
export const FETCH_ALL_CATEGORIES = 'FETCH_ALL_CATEGORIES';
export const FETCH_FAILURE = 'FETCH_FAILURE';
export const SET_EXERCISE = 'SET_EXERCISE';
export const SET_SOLUTION = 'SET_SOLUTION';
export const EDIT_EXERCISE = 'EDIT_SENTENCE';
export const EDIT_SOLUTION_INDEX ='EDIT_SOLUTION_INDEX';
export const EDIT_SOLUTION_CATEGORY = 'EDIT_SOLUTION_CATEGORY';